[profile.default]
# forge config
fuzz-runs = 100
verbosity = 3
# solidity config
solc-version = "0.8.13"
optimizer = true
optimizer-runs = 9999999
fs_permissions = [{ access = "read-write", path = "./"}]

[profile.ci]
fuzz-runs = 500

[rpc_endpoints]
mainnet = "${RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
